server.port=8090
spring.application.name=pasarela

zuul.sensitiveHeaders=

zuul.routes.productos.path=/productos/**
zuul.routes.productos.url=http://productos:8080/

zuul.routes.compraventas.path=/compraventas/**
zuul.routes.compraventas.url=http://compraventas:8081/

zuul.routes.usuarios.path=/usuarios/**
zuul.routes.usuarios.url=http://usuarios:8082/api

spring.security.oauth2.client.registration.github.client-id=Ov23li1l5u6GwOWnVeyu
spring.security.oauth2.client.registration.github.client-secret=fc9bb470683b91670f566150d30dcd8bb3436bab