spring.application.name=microservicio-compraventas

server.port=8081

spring.data.mongodb.uri=mongodb+srv://jabier:jabier@cluster0.mongodb.net/?appName=Cluster0


logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

