# Nombre de tu aplicación
spring.application.name=microservicio-compraventas

# PUERTO: Muy importante usar el 8081 para que no choque con Productos (8080)
server.port=8081

# CONEXIÓN A MONGODB ATLAS
# Sustituye <usuario>, <password> y <cluster> por los tuyos reales de MongoDB Atlas.
spring.data.mongodb.uri=mongodb+srv://jabier:jabier@cluster0.mongodb.net/?appName=Cluster0

# Para ver las consultas de Mongo en la consola (opcional pero útil)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG